# Edit and rename to `.secrets.toml`
[rafo]
# Date (in ISO format) until which the legacy URLs will be accepted.
baserow_api_key = ""
smtp_sender_address = ""
smtp_host = ""
smtp_user = ""
smtp_password = ""
smtp_port = ""
omnia_domain_id = ""
omnia_api_secret = ""
omnia_session_id = ""
# Date (in ISO format) until which the legacy URLs will be accepted.
webhook_secret = ""
ntfy_topic = ""